modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="badideasmod"
version="1.0.0"
displayName="BAD_IDEAS_MOD"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Wildstone"

[[dependencies.badideasmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



